### ISSUE TITLE
create a retry loop in timeout!

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/github-supported-languages#7]
https://github.com/prabhakar267/github-supported-languages/blob/master/main.py#L34
If there is a timeout exception, create a loop to get the results again!

**Comment by adityajain21** [comment]
If someone is not working on it, then I would like to work on it?

**Comment by prabhakar267** [comment]
@adityajain21 yes you can work on it :+1:

**Comment by vctrmagno** [comment]
Sent PR #9

**Comment by prabhakar267** [comment]
@vctrmagno thanks for the PR
merged!

**Comment by vctrmagno** [comment]
No problem, man! :)
